src/main/java/com/cejv559/databeans/LanguageBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cejv559.databeans;

import java.io.Serializable;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import javax.enterprise.context.SessionScoped;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.faces.event.ValueChangeEvent;

/**
 *
 * @author uwij002
 */
    @ManagedBean
    @SessionScoped
    public class LanguageBean implements Serializable{

	private String localeCode;

	private static Map<String,Object> countries;
	static{
		countries = new LinkedHashMap<String,Object>();
		countries.put("English", Locale.ENGLISH); //label, value
		countries.put("French", Locale.CANADA_FRENCH);
	}

	public Map<String, Object> getCountriesInMap() {
		return countries;
	}


	public String getLocaleCode() {
		return localeCode;
	}


	public void setLocaleCode(String localeCode) {
		this.localeCode = localeCode;
	}

	//value change event listener
	public void countryLocaleCodeChanged(ValueChangeEvent e){

		String newLocaleValue = e.getNewValue().toString();

		//loop country map to compare the locale code
                for (Map.Entry<String, Object> entry : countries.entrySet()) {

        	   if(entry.getValue().toString().equals(newLocaleValue)){

        		FacesContext.getCurrentInstance()
        			.getViewRoot().setLocale((Locale)entry.getValue());

        	  }
               }
	}
}

src/main/webapp/any7Lose.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Any 7 Result</title>
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css"/>
    </h:head>
    <h:body>
        <f:view locale="#{languageBean.localeCode}">
            <h:form id="Casino_App">
                <div>
                    <ui:insert name="header" >
                        <ui:include src="header.xhtml" />
                    </ui:insert>
                </div>

                <div>
                    <h3 style="text-align: center"><h:outputLabel value="#{bundle.any7Label}"/></h3>

                    <b:panelGrid colSpans="11,1" offset-xs="2">
                        <b:panel title="#{bundle.gameRulesLabel}" look="info">
                            <h:outputText value="#{bundle.any7Rule}" />
                        </b:panel>
                    </b:panelGrid>
                    <b:panelGrid colSpans="11,1">
                        <b:alert  severity="danger"><strong>#{bankroll.money != 0 ? bundle.any7Lose: bundle.gameOver}</strong></b:alert>
                    </b:panelGrid>
                    <b:panelGrid colSpans="2,4,6" style="margin: 0 20px 0 0;">
                        <h:outputText value="#{bundle.bankrollLabel}"/>
                        <b:inputText value="#{bankroll.money}" readonly="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                        </b:inputText>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.betAmountLabel}"/>
                        <b:inputText value="#{bankroll.bet}" id="bet" required="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                            <f:validateDoubleRange minimum="1" maximum="#{bankroll.money}"/>
                        </b:inputText>
                        <h:message for="bet" style="color:red" />
                        <h:outputText id="dieOne" value="#{bundle.dieOneLabel}" rendered="#{dice.die1 != 0}"/>
                        <b:icon name="die1" class="#{dice.classNameDieOne}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.dieTwoLabel}" rendered="#{dice.die2 != 0}"/>
                        <b:icon name="die1" class="#{dice.classNameDieTwo}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />

                    </b:panelGrid>

                    <b:panelGrid colSpans="12">
                        <b:commandButton value="#{bundle.rollMessage}" style="margin-top: 20px;" action="#{theGames.any7}" col-sm="1" class="btn-primary"/>

                    </b:panelGrid>


                </div>


                <ui:insert name="footer" >
                    <ui:include src="footer.xhtml" />
                </ui:insert>

            </h:form>
        </f:view>
    </h:body>
</html>

src/main/webapp/fieldBetWin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Field Bet Result</title>
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css"/>
    </h:head>
    <h:body>
        <f:view locale="#{languageBean.localeCode}">
            <h:form id="Casino_App">
                <div>
                    <ui:insert name="header" >
                        <ui:include src="header.xhtml" />
                    </ui:insert>
                </div>

                <div>
                    <h3 style="text-align: center"><h:outputLabel value="#{bundle.fieldLabel}"/></h3>
                    <b:panelGrid colSpans="11,1" offset-xs="2">
                        <b:panel title="#{bundle.gameRulesLabel}" look="info">
                            <h:outputText value="#{bundle.fieldRule}" />
                        </b:panel>
                    </b:panelGrid>
                    <b:panelGrid colSpans="11,1">
                        <b:alert severity="success"><strong>#{bundle.fieldWin}</strong></b:alert>
                    </b:panelGrid>
                    <b:panelGrid colSpans="2,4,6" style="margin: 10px 20px 0 0;">
                        <h:outputText value="#{bundle.bankrollLabel}"/>
                        <b:inputText value="#{bankroll.money}" readonly="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                        </b:inputText>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.betAmountLabel}"/>
                        <b:inputText value="#{bankroll.bet}" id="bet" required="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                            <f:validateDoubleRange minimum="1" maximum="#{bankroll.money}"/>
                        </b:inputText>
                        <h:message for="bet" style="color:red" />
                        <h:outputText id="dieOne" value="#{bundle.dieOneLabel}" rendered="#{dice.die1 != 0}"/>
                        <b:icon name="die1" class="#{dice.classNameDieOne}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.dieTwoLabel}" rendered="#{dice.die2 != 0}"/>
                        <b:icon name="die2" class="#{dice.classNameDieTwo}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />

                    </b:panelGrid>

                    <b:panelGrid colSpans="12">
                        <b:commandButton value="#{bundle.rollMessage}" style="margin-top: 20px;" action="#{theGames.fieldBet}" col-sm="1" class="btn-primary"/>

                    </b:panelGrid>


                </div>


                <ui:insert name="footer">
                    <ui:include src="footer.xhtml" />
                </ui:insert>

            </h:form>
        </f:view>
    </h:body>
</html>

src/main/webapp/fieldDoubleWin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Any 7 Result</title>
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css"/>
    </h:head>
    <h:body>
        <f:view locale="#{languageBean.localeCode}">
            <h:form id="Casino_App">
                <div>
                    <ui:insert name="header" >
                        <ui:include src="header.xhtml" />
                    </ui:insert>
                </div>

                <div>
                    <h3 style="text-align: center"><h:outputLabel value="#{bundle.fieldLabel}"/></h3>
                    <b:panelGrid colSpans="11,1" offset-xs="2">
                        <b:panel title="#{bundle.gameRulesLabel}" look="info">
                            <h:outputText value="#{bundle.fieldRule}" />
                        </b:panel>
                    </b:panelGrid>
                    <b:panelGrid colSpans="11,1">
                        <b:alert severity="success"><strong>#{bundle.fieldDoubleWin}</strong></b:alert>
                    </b:panelGrid>
                    <b:panelGrid colSpans="2,4,6" style="margin: 10px 20px 0 0;">
                        <h:outputText value="#{bundle.bankrollLabel}"/>
                       <b:inputText value="#{bankroll.money}" readonly="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                        </b:inputText>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.betAmountLabel}"/>
                        <b:inputText value="#{bankroll.bet}" id="bet" required="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                            <f:validateDoubleRange minimum="1" maximum="#{bankroll.money}"/>
                        </b:inputText>
                        <h:message for="bet" style="color:red" />
                        <h:outputText id="dieOne" value="#{bundle.dieOneLabel}" rendered="#{dice.die1 != 0}"/>
                        <b:icon name="die1" class="#{dice.classNameDieOne}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.dieTwoLabel}" rendered="#{dice.die2 != 0}"/>
                        <b:icon name="die2" class="#{dice.classNameDieTwo}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />

                    </b:panelGrid>

                    <b:panelGrid colSpans="12">
                        <b:commandButton value="#{bundle.rollMessage}" style="margin-top: 20px;" action="#{theGames.fieldBet}" col-sm="1" class="btn-primary"/>

                    </b:panelGrid>


                </div>


                <ui:insert name="footer" >
                    <ui:include src="footer.xhtml" />
                </ui:insert>

            </h:form>
        </f:view>
    </h:body>
</html>

src/main/webapp/fieldLose.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Any 7 Result</title>
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css"/>
    </h:head>
    <h:body>
        <f:view locale="#{languageBean.localeCode}">
            <h:form id="Casino_App">
                <div>
                    <ui:insert name="header" >
                        <ui:include src="header.xhtml" />
                    </ui:insert>
                </div>

                <div>
                    <h3 style="text-align: center"><h:outputLabel value="#{bundle.fieldLabel}"/></h3>
                    <b:panelGrid colSpans="11,1" offset-xs="2">
                        <b:panel title="#{bundle.gameRulesLabel}" look="info">
                            <h:outputText value="#{bundle.fieldRule}" />
                        </b:panel>
                    </b:panelGrid>
                    <b:panelGrid colSpans="11,1">
                        <b:alert  severity="danger"><strong>#{bankroll.money != 0 ? bundle.fieldBetLose: bundle.gameOver}</strong></b:alert>
                    </b:panelGrid>

                    <b:panelGrid colSpans="2,4,6" style="margin: 10px 20px 0 0;">
                        <h:outputText value="#{bundle.bankrollLabel}"/>
                        <b:inputText value="#{bankroll.money}" readonly="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                        </b:inputText>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.betAmountLabel}"/>
                        <b:inputText value="#{bankroll.bet}" id="bet" required="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                            <f:validateDoubleRange minimum="1" maximum="#{bankroll.money}"/>
                        </b:inputText>
                        <h:message for="bet" style="color:red" />
                        <h:outputText id="dieOne" value="#{bundle.dieOneLabel}" rendered="#{dice.die1 != 0}"/>
                        <b:icon name="die1" class="#{dice.classNameDieOne}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.dieTwoLabel}" rendered="#{dice.die2 != 0}"/>
                        <b:icon name="die2" class="#{dice.classNameDieTwo}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />

                    </b:panelGrid>

                    <b:panelGrid colSpans="12">
                        <b:commandButton value="#{bundle.rollMessage}" style="margin-top: 20px;" action="#{theGames.fieldBet}" col-sm="1" class="btn-primary"/>

                    </b:panelGrid>


                </div>


                <ui:insert name="footer" >
                    <ui:include src="footer.xhtml" />
                </ui:insert>

            </h:form>
        </f:view>
    </h:body>
</html>

src/main/webapp/fieldTripleWin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Any 7 Result</title>
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css"/>
    </h:head>
    <h:body>
        <f:view locale="#{languageBean.localeCode}">
            <h:form id="Casino_App">
                <div>
                    <ui:insert name="header" >
                        <ui:include src="header.xhtml" />
                    </ui:insert>
                </div>

                <div>
                    <h3 style="text-align: center"><h:outputLabel value="#{bundle.fieldLabel}"/></h3>
                    <b:panelGrid colSpans="11,1" offset-xs="2">

                        <b:panel title="#{bundle.gameRulesLabel}" look="info">
                            <h:outputText value="#{bundle.fieldRule}" />
                        </b:panel>
                    </b:panelGrid>
                    <b:panelGrid colSpans="11,1">
                        <b:alert severity="success"><strong>#{bundle.fieldTripleWin}</strong></b:alert>
                    </b:panelGrid>
                    <b:panelGrid colSpans="2,4,6" style="margin: 10px 20px 0 0;">
                        <h:outputText value="#{bundle.bankrollLabel}"/>
                        <b:inputText value="#{bankroll.money}" readonly="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                        </b:inputText>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.betAmountLabel}"/>
                        <b:inputText value="#{bankroll.bet}" id="bet" required="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                            <f:validateDoubleRange minimum="1" maximum="#{bankroll.money}"/>
                        </b:inputText>
                        <h:message for="bet" style="color:red" />
                        <h:outputText id="dieOne" value="#{bundle.dieOneLabel}" rendered="#{dice.die1 != 0}"/>
                        <b:icon name="die1" class="#{dice.classNameDieOne}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.dieTwoLabel}" rendered="#{dice.die2 != 0}"/>
                        <b:icon name="die2" class="#{dice.classNameDieTwo}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />

                    </b:panelGrid>

                    <b:panelGrid colSpans="12">
                        <b:commandButton value="#{bundle.rollMessage}" style="margin-top: 20px;" action="#{theGames.fieldBet}" col-sm="1" class="btn-primary"/>

                    </b:panelGrid>


                </div>


                <ui:insert name="footer" >
                    <ui:include src="footer.xhtml" />
                </ui:insert>

            </h:form>
        </f:view>
    </h:body>
</html>

src/main/webapp/field_bet.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui">
    <h:head>
        <title>Field Bet</title>
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css"/>
    </h:head>
    <h:body>
        <f:view locale="#{languageBean.localeCode}">
            <h:form id="Casino_App">
                <div>
                    <ui:insert name="header" >
                        <ui:include src="header.xhtml" />
                    </ui:insert>
                </div>

                <div>
                    <h3 style="text-align: center"><h:outputText value="#{bundle.fieldLabel}"/></h3>
                    <b:panelGrid colSpans="11,1" offset-xs="2">

                        <b:panel title="#{bundle.gameRulesLabel}" look="info">
                            <h:outputText value="#{bundle.fieldRule}" />
                        </b:panel>

                    </b:panelGrid>

                    <b:panelGrid colSpans="2,4,6" style="margin:0 20px 0 0;">
                        <h:outputText value="#{bundle.betAmountLabel}"/>
                        <b:inputText value="#{bankroll.bet}" id="bet" required="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                            <f:validateDoubleRange minimum="1" maximum="#{bankroll.money}"/>
                        </b:inputText>
                        <h:message for="bet" style="color:red" />
                        <h:outputText id="dieOne" value="#{bundle.dieOneLabel}" rendered="#{dice.die1 != 0}"/>
                        <b:icon name="die1" class="#{dice.classNameDieOne}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />
                        <h:outputText value="#{bundle.dieTwoLabel}" rendered="#{dice.die2 != 0}"/>
                        <b:icon name="die2" class="#{dice.classNameDieTwo}" style="font-size: 40px;"/>
                        <h:message for="" style="color:red" />

                    </b:panelGrid>

                    <b:panelGrid colSpans="12">
                        <b:commandButton value="#{bundle.rollMessage}" style="margin-top: 20px;" action="#{theGames.fieldBet}" col-sm="1" class="btn-primary"/>

                    </b:panelGrid>


                </div>


                <ui:insert name="footer" >
                    <ui:include src="footer.xhtml" />
                </ui:insert>

            </h:form>
        </f:view>
    </h:body>
</html>

src/main/webapp/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui">

    <h:body>
        <ui:composition>
            <nav class="navbar-default navbar-fixed-bottom" style="height: 22px; padding-top: 5px;">
                <div class="container-fluid">
                    <p class=" text-center small"> <b:iconAwesome name="copyright" /> 2017 Jean Claude Uwimpuhwe, CEJV 559 LAB 02</p>
                </div>
            </nav>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:b="http://bootsfaces.net/ui">

    <h:body>
        <ui:composition>
            <b:navBar inverse="true">
                    <b:navbarLinks>
                        <b:navLink icon-awesome="diamond" value="Craps Casino" iconSpin="true" icon-size="lg" href="#"/>
                        <b:navCommandLink action="index" iconAwesome="home" value="Home" />
                        
                        
                    </b:navbarLinks>
                    
                </b:navBar>
            <h:selectOneMenu value="#{languageBean.localeCode}" onchange="submit()"  
                             style="margin: 0 20px; float: right"
                             valueChangeListener="#{languageBean.countryLocaleCodeChanged}">
                <f:selectItems value="#{languageBean.countriesInMap}" />
                

            </h:selectOneMenu>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/header_home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    
    <h:body>
        <ui:composition>
            <b:navBar inverse="true">
                    <b:navbarLinks>
                        <b:navLink icon-awesome="diamond" value="Craps Casino" iconSpin="true" icon-size="lg" href="#"/>
                        
                        
                        
                    </b:navbarLinks>
                    
                </b:navBar>
            
           
            <h:selectOneMenu  value="#{languageBean.localeCode}" onchange="submit()"  
                             style="margin: 0 20px; float: right;"
                             valueChangeListener="#{languageBean.countryLocaleCodeChanged}">
                <f:selectItems value="#{languageBean.countriesInMap}" />
                

            </h:selectOneMenu>
           
        </ui:composition>
    </h:body>
</html>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:head>
        <title>Casino App</title>
        <link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css"/>
    </h:head>
    <h:body>
        <f:view locale="#{languageBean.localeCode}">
            <h:form id="Casino_App">


                <ui:insert name="header" >
                    <ui:include src="header_home.xhtml" />
                </ui:insert>




                <b:well style="margin-top: 100px;">
                    <h3 class="text-center"><p:outputLabel value="#{bundle.appTitle}" style="margin: 20px;" class="success" /></h3>

                    <b:panelGrid colSpans="2,4,6" style="margin: 20px 20px 20px 0;"  offset-xs="4">

                        <h:outputText value="#{bundle.bankrollLabel}"/>
                        <b:inputText id="bankroll" required="true" value="#{bankroll.money}" readonly="#{bankroll.money != 0}">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                            <f:validateDoubleRange minimum="100" />
                        </b:inputText>
                        <h:message for="bankroll" style="color:red" />
                        <h:outputText value="#{bundle.betAmountLabel}"/>
                        <b:inputText value="#{bankroll.bet}" id="bet" required="true">
                            <f:facet name="prepend">
                                <h:outputText value="$" />
                            </f:facet>
                            <f:validateDoubleRange minimum="1" maximum="100"/>
                        </b:inputText>
                        <h:message for="bet" style="color:red" />
                    </b:panelGrid>

                    <h:panelGrid columns="3" style="margin: 0 auto">
                        <b:commandButton value="Pass Line" style="margin: 5px;" action="pass_line" style-class="btn-primary"/>
                        <b:commandButton value="Field Bet" style="margin: 5px;" action="field_bet" style-class="btn-primary"/>
                        <b:commandButton value="Any Seven" style="margin: 5px;" action="any7" style-class="btn-primary"/>

                    </h:panelGrid>


                </b:well>
                <ui:insert name="footer" >
                    <ui:include src="footer.xhtml" />
                </ui:insert>




            </h:form>

        </f:view>
    </h:body>
</html>